package com.ai.dev.mapper.interfaces;

import com.ai.dev.mapper.vo.TpGis;
import com.ai.dev.mapper.vo.TpGisCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpGisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    long countByExample(TpGisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int deleteByExample(TpGisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int insert(TpGis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int insertSelective(TpGis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    List<TpGis> selectByExample(TpGisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    TpGis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TpGis record, @Param("example") TpGisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TpGis record, @Param("example") TpGisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TpGis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TpGis record);
}