package com.ai.dev.mapper.interfaces;

import com.ai.dev.mapper.vo.TpHttpCase;
import com.ai.dev.mapper.vo.TpHttpCaseCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpHttpCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    long countByExample(TpHttpCaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int deleteByExample(TpHttpCaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int insert(TpHttpCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int insertSelective(TpHttpCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    List<TpHttpCase> selectByExample(TpHttpCaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    TpHttpCase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TpHttpCase record, @Param("example") TpHttpCaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TpHttpCase record, @Param("example") TpHttpCaseCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TpHttpCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_http_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TpHttpCase record);
}