package com.ai.dev.mapper.interfaces;

import com.ai.dev.mapper.vo.TpTestsuite;
import com.ai.dev.mapper.vo.TpTestsuiteCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpTestsuiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    long countByExample(TpTestsuiteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int deleteByExample(TpTestsuiteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int insert(TpTestsuite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int insertSelective(TpTestsuite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    List<TpTestsuite> selectByExample(TpTestsuiteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    TpTestsuite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TpTestsuite record, @Param("example") TpTestsuiteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TpTestsuite record, @Param("example") TpTestsuiteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TpTestsuite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TpTestsuite record);
}