package com.ai.dev.mapper.vo;

import java.io.Serializable;
import java.util.Date;

public class THttpcase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.system_name
     *
     * @mbg.generated
     */
    private String systemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.case_name
     *
     * @mbg.generated
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.case_desc
     *
     * @mbg.generated
     */
    private String caseDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.case_groups
     *
     * @mbg.generated
     */
    private String caseGroups;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.uri
     *
     * @mbg.generated
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.header
     *
     * @mbg.generated
     */
    private String header;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.request_body
     *
     * @mbg.generated
     */
    private String requestBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.check_sql
     *
     * @mbg.generated
     */
    private String checkSql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.expected_result
     *
     * @mbg.generated
     */
    private String expectedResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.operate_user
     *
     * @mbg.generated
     */
    private String operateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_httpCase.is_valid
     *
     * @mbg.generated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_httpCase
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.id
     *
     * @return the value of t_httpCase.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.id
     *
     * @param id the value for t_httpCase.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.case_id
     *
     * @return the value of t_httpCase.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.case_id
     *
     * @param caseId the value for t_httpCase.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.system_name
     *
     * @return the value of t_httpCase.system_name
     *
     * @mbg.generated
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.system_name
     *
     * @param systemName the value for t_httpCase.system_name
     *
     * @mbg.generated
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.case_name
     *
     * @return the value of t_httpCase.case_name
     *
     * @mbg.generated
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.case_name
     *
     * @param caseName the value for t_httpCase.case_name
     *
     * @mbg.generated
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.case_desc
     *
     * @return the value of t_httpCase.case_desc
     *
     * @mbg.generated
     */
    public String getCaseDesc() {
        return caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.case_desc
     *
     * @param caseDesc the value for t_httpCase.case_desc
     *
     * @mbg.generated
     */
    public void setCaseDesc(String caseDesc) {
        this.caseDesc = caseDesc == null ? null : caseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.case_groups
     *
     * @return the value of t_httpCase.case_groups
     *
     * @mbg.generated
     */
    public String getCaseGroups() {
        return caseGroups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.case_groups
     *
     * @param caseGroups the value for t_httpCase.case_groups
     *
     * @mbg.generated
     */
    public void setCaseGroups(String caseGroups) {
        this.caseGroups = caseGroups == null ? null : caseGroups.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.uri
     *
     * @return the value of t_httpCase.uri
     *
     * @mbg.generated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.uri
     *
     * @param uri the value for t_httpCase.uri
     *
     * @mbg.generated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.port
     *
     * @return the value of t_httpCase.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.port
     *
     * @param port the value for t_httpCase.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.header
     *
     * @return the value of t_httpCase.header
     *
     * @mbg.generated
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.header
     *
     * @param header the value for t_httpCase.header
     *
     * @mbg.generated
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.request_body
     *
     * @return the value of t_httpCase.request_body
     *
     * @mbg.generated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.request_body
     *
     * @param requestBody the value for t_httpCase.request_body
     *
     * @mbg.generated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody == null ? null : requestBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.check_sql
     *
     * @return the value of t_httpCase.check_sql
     *
     * @mbg.generated
     */
    public String getCheckSql() {
        return checkSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.check_sql
     *
     * @param checkSql the value for t_httpCase.check_sql
     *
     * @mbg.generated
     */
    public void setCheckSql(String checkSql) {
        this.checkSql = checkSql == null ? null : checkSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.expected_result
     *
     * @return the value of t_httpCase.expected_result
     *
     * @mbg.generated
     */
    public String getExpectedResult() {
        return expectedResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.expected_result
     *
     * @param expectedResult the value for t_httpCase.expected_result
     *
     * @mbg.generated
     */
    public void setExpectedResult(String expectedResult) {
        this.expectedResult = expectedResult == null ? null : expectedResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.create_user
     *
     * @return the value of t_httpCase.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.create_user
     *
     * @param createUser the value for t_httpCase.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.create_date
     *
     * @return the value of t_httpCase.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.create_date
     *
     * @param createDate the value for t_httpCase.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.operate_user
     *
     * @return the value of t_httpCase.operate_user
     *
     * @mbg.generated
     */
    public String getOperateUser() {
        return operateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.operate_user
     *
     * @param operateUser the value for t_httpCase.operate_user
     *
     * @mbg.generated
     */
    public void setOperateUser(String operateUser) {
        this.operateUser = operateUser == null ? null : operateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.update_date
     *
     * @return the value of t_httpCase.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.update_date
     *
     * @param updateDate the value for t_httpCase.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_httpCase.is_valid
     *
     * @return the value of t_httpCase.is_valid
     *
     * @mbg.generated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_httpCase.is_valid
     *
     * @param isValid the value for t_httpCase.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}