package com.ai.dev.mapper.vo;

import java.io.Serializable;

public class TpGis implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_gis.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_gis.source_addr
     *
     * @mbg.generated
     */
    private String sourceAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_gis.source_location
     *
     * @mbg.generated
     */
    private String sourceLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_gis.source_xy
     *
     * @mbg.generated
     */
    private String sourceXy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_gis
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_gis.id
     *
     * @return the value of tp_gis.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_gis.id
     *
     * @param id the value for tp_gis.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_gis.source_addr
     *
     * @return the value of tp_gis.source_addr
     *
     * @mbg.generated
     */
    public String getSourceAddr() {
        return sourceAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_gis.source_addr
     *
     * @param sourceAddr the value for tp_gis.source_addr
     *
     * @mbg.generated
     */
    public void setSourceAddr(String sourceAddr) {
        this.sourceAddr = sourceAddr == null ? null : sourceAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_gis.source_location
     *
     * @return the value of tp_gis.source_location
     *
     * @mbg.generated
     */
    public String getSourceLocation() {
        return sourceLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_gis.source_location
     *
     * @param sourceLocation the value for tp_gis.source_location
     *
     * @mbg.generated
     */
    public void setSourceLocation(String sourceLocation) {
        this.sourceLocation = sourceLocation == null ? null : sourceLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_gis.source_xy
     *
     * @return the value of tp_gis.source_xy
     *
     * @mbg.generated
     */
    public String getSourceXy() {
        return sourceXy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_gis.source_xy
     *
     * @param sourceXy the value for tp_gis.source_xy
     *
     * @mbg.generated
     */
    public void setSourceXy(String sourceXy) {
        this.sourceXy = sourceXy == null ? null : sourceXy.trim();
    }
}