package com.ai.dev.mapper.vo;

import java.io.Serializable;
import java.util.Date;

public class TpTestsuite implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.case_desc
     *
     * @mbg.generated
     */
    private String caseDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.case_groups
     *
     * @mbg.generated
     */
    private String caseGroups;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.is_run_group
     *
     * @mbg.generated
     */
    private Integer isRunGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.create_owner
     *
     * @mbg.generated
     */
    private String createOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_testsuite.is_valid
     *
     * @mbg.generated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.id
     *
     * @return the value of tp_testsuite.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.id
     *
     * @param id the value for tp_testsuite.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.case_id
     *
     * @return the value of tp_testsuite.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.case_id
     *
     * @param caseId the value for tp_testsuite.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.case_desc
     *
     * @return the value of tp_testsuite.case_desc
     *
     * @mbg.generated
     */
    public String getCaseDesc() {
        return caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.case_desc
     *
     * @param caseDesc the value for tp_testsuite.case_desc
     *
     * @mbg.generated
     */
    public void setCaseDesc(String caseDesc) {
        this.caseDesc = caseDesc == null ? null : caseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.case_groups
     *
     * @return the value of tp_testsuite.case_groups
     *
     * @mbg.generated
     */
    public String getCaseGroups() {
        return caseGroups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.case_groups
     *
     * @param caseGroups the value for tp_testsuite.case_groups
     *
     * @mbg.generated
     */
    public void setCaseGroups(String caseGroups) {
        this.caseGroups = caseGroups == null ? null : caseGroups.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.is_run_group
     *
     * @return the value of tp_testsuite.is_run_group
     *
     * @mbg.generated
     */
    public Integer getIsRunGroup() {
        return isRunGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.is_run_group
     *
     * @param isRunGroup the value for tp_testsuite.is_run_group
     *
     * @mbg.generated
     */
    public void setIsRunGroup(Integer isRunGroup) {
        this.isRunGroup = isRunGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.update_date
     *
     * @return the value of tp_testsuite.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.update_date
     *
     * @param updateDate the value for tp_testsuite.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.create_date
     *
     * @return the value of tp_testsuite.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.create_date
     *
     * @param createDate the value for tp_testsuite.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.create_owner
     *
     * @return the value of tp_testsuite.create_owner
     *
     * @mbg.generated
     */
    public String getCreateOwner() {
        return createOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.create_owner
     *
     * @param createOwner the value for tp_testsuite.create_owner
     *
     * @mbg.generated
     */
    public void setCreateOwner(String createOwner) {
        this.createOwner = createOwner == null ? null : createOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_testsuite.is_valid
     *
     * @return the value of tp_testsuite.is_valid
     *
     * @mbg.generated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_testsuite.is_valid
     *
     * @param isValid the value for tp_testsuite.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}