package com.ai.dev.mapper.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TpTestsuiteCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public TpTestsuiteCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNull() {
            addCriterion("case_id is null");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNotNull() {
            addCriterion("case_id is not null");
            return (Criteria) this;
        }

        public Criteria andCaseIdEqualTo(String value) {
            addCriterion("case_id =", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotEqualTo(String value) {
            addCriterion("case_id <>", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThan(String value) {
            addCriterion("case_id >", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("case_id >=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThan(String value) {
            addCriterion("case_id <", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThanOrEqualTo(String value) {
            addCriterion("case_id <=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLike(String value) {
            addCriterion("case_id like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotLike(String value) {
            addCriterion("case_id not like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdIn(List<String> values) {
            addCriterion("case_id in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotIn(List<String> values) {
            addCriterion("case_id not in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdBetween(String value1, String value2) {
            addCriterion("case_id between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotBetween(String value1, String value2) {
            addCriterion("case_id not between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseDescIsNull() {
            addCriterion("case_desc is null");
            return (Criteria) this;
        }

        public Criteria andCaseDescIsNotNull() {
            addCriterion("case_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCaseDescEqualTo(String value) {
            addCriterion("case_desc =", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescNotEqualTo(String value) {
            addCriterion("case_desc <>", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescGreaterThan(String value) {
            addCriterion("case_desc >", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescGreaterThanOrEqualTo(String value) {
            addCriterion("case_desc >=", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescLessThan(String value) {
            addCriterion("case_desc <", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescLessThanOrEqualTo(String value) {
            addCriterion("case_desc <=", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescLike(String value) {
            addCriterion("case_desc like", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescNotLike(String value) {
            addCriterion("case_desc not like", value, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescIn(List<String> values) {
            addCriterion("case_desc in", values, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescNotIn(List<String> values) {
            addCriterion("case_desc not in", values, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescBetween(String value1, String value2) {
            addCriterion("case_desc between", value1, value2, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseDescNotBetween(String value1, String value2) {
            addCriterion("case_desc not between", value1, value2, "caseDesc");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsIsNull() {
            addCriterion("case_groups is null");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsIsNotNull() {
            addCriterion("case_groups is not null");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsEqualTo(String value) {
            addCriterion("case_groups =", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsNotEqualTo(String value) {
            addCriterion("case_groups <>", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsGreaterThan(String value) {
            addCriterion("case_groups >", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsGreaterThanOrEqualTo(String value) {
            addCriterion("case_groups >=", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsLessThan(String value) {
            addCriterion("case_groups <", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsLessThanOrEqualTo(String value) {
            addCriterion("case_groups <=", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsLike(String value) {
            addCriterion("case_groups like", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsNotLike(String value) {
            addCriterion("case_groups not like", value, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsIn(List<String> values) {
            addCriterion("case_groups in", values, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsNotIn(List<String> values) {
            addCriterion("case_groups not in", values, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsBetween(String value1, String value2) {
            addCriterion("case_groups between", value1, value2, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andCaseGroupsNotBetween(String value1, String value2) {
            addCriterion("case_groups not between", value1, value2, "caseGroups");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupIsNull() {
            addCriterion("is_run_group is null");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupIsNotNull() {
            addCriterion("is_run_group is not null");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupEqualTo(Integer value) {
            addCriterion("is_run_group =", value, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupNotEqualTo(Integer value) {
            addCriterion("is_run_group <>", value, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupGreaterThan(Integer value) {
            addCriterion("is_run_group >", value, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_run_group >=", value, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupLessThan(Integer value) {
            addCriterion("is_run_group <", value, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupLessThanOrEqualTo(Integer value) {
            addCriterion("is_run_group <=", value, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupIn(List<Integer> values) {
            addCriterion("is_run_group in", values, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupNotIn(List<Integer> values) {
            addCriterion("is_run_group not in", values, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupBetween(Integer value1, Integer value2) {
            addCriterion("is_run_group between", value1, value2, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andIsRunGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("is_run_group not between", value1, value2, "isRunGroup");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerIsNull() {
            addCriterion("create_owner is null");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerIsNotNull() {
            addCriterion("create_owner is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerEqualTo(String value) {
            addCriterion("create_owner =", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerNotEqualTo(String value) {
            addCriterion("create_owner <>", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerGreaterThan(String value) {
            addCriterion("create_owner >", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("create_owner >=", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerLessThan(String value) {
            addCriterion("create_owner <", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerLessThanOrEqualTo(String value) {
            addCriterion("create_owner <=", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerLike(String value) {
            addCriterion("create_owner like", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerNotLike(String value) {
            addCriterion("create_owner not like", value, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerIn(List<String> values) {
            addCriterion("create_owner in", values, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerNotIn(List<String> values) {
            addCriterion("create_owner not in", values, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerBetween(String value1, String value2) {
            addCriterion("create_owner between", value1, value2, "createOwner");
            return (Criteria) this;
        }

        public Criteria andCreateOwnerNotBetween(String value1, String value2) {
            addCriterion("create_owner not between", value1, value2, "createOwner");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Integer value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Integer value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Integer value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Integer value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Integer value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Integer> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Integer> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Integer value1, Integer value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Integer value1, Integer value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_testsuite
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_testsuite
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}