server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/oldface?useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:cashc0wA}
    druid:
      keep-alive: true
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      log-abandoned: true

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.ai.dev.mapper.vo
  type-handlers-package: com.ai.dev.mapper.interface
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  autoRuntimeDialect: true


